"""add_changelog_table

Revision ID: 3770ac219d03
Revises: ddddddddddddd
Create Date: 2026-02-11 20:38:01.885056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3770ac219d03'
down_revision: Union[str, Sequence[str], None] = 'ddddddddddddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_changelog_version'), 'changelog', ['version'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_configs', sa.Column('params_json', sa.TEXT(), nullable=True))
    op.drop_constraint('uq_user_persona', 'strategy_configs', type_='unique')
    op.create_unique_constraint(op.f('uq_user_strategy'), 'strategy_configs', ['user_id', 'strategy_id'])
    op.drop_column('strategy_configs', 'is_public')
    op.drop_column('strategy_configs', 'icon')
    op.drop_column('strategy_configs', 'color')
    op.drop_column('strategy_configs', 'expected_roi')
    op.drop_column('strategy_configs', 'risk_profile')
    op.drop_column('strategy_configs', 'description')
    op.drop_column('strategy_configs', 'name')
    op.drop_index(op.f('ix_changelog_version'), table_name='changelog')
    op.drop_table('changelog')
    # ### end Alembic commands ###
